---
upload_path: "/assets/images/uploads/header"
frontmatter_file_url_template: "/assets/images/uploads/header"
body_file_url_template: "/assets/images/uploads/body/:year"
new_page_extension: md
auto_deploy: false
admin_path: "/admin/"
webhook_url: 
collections: 
